# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "07b07fd6a2b788abc9a281eaa5a64427"
application_url = "https://tired-saving-band-voices.trycloudflare.com"
embedded = true
name = "product-management"
handle = "product-management-30"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tired-saving-band-voices.trycloudflare.com/auth/callback",
  "https://tired-saving-band-voices.trycloudflare.com/auth/shopify/callback",
  "https://tired-saving-band-voices.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
